### ISSUE TITLE
Skipping on save events

### ISSUE THREAD

**Issue by bensheridanreason** [nathanwoulfe/Plumber-2#130]
I have added  a hook on save, this works fine if when using the inbuilt save/publish flow but when something is sent to be approved it dose not trigger the checks.

**To Reproduce**
The hook is registered like below:
`

    [RuntimeLevel(MinLevel = RuntimeLevel.Run)]
    public class OnSavingHookComposer : ComponentComposer<OnSavingHookComponent>
    {
    }

    public class OnSavingHookComponent : IComponent
    {

        public void Initialize()
        {
            ContentService.Saving += ContentService_Saving;
        }

        private static void ContentService_Saving(Umbraco.Core.Services.IContentService sender,
            Umbraco.Core.Events.ContentSavingEventArgs e)
        {
            foreach (var node in e.SavedEntities)
            {
               //code to process checks here

            }

        }

        public void Terminate()
        {
            //unsubscribe during shutdown
            ContentService.Saving -= ContentService_Saving;
        }
    }
`

**Expected behavior**
The above hook is triggered

**Plumber version**
2.1.7 umbraco 8

**Licensed version?**
yes blind veterans

**Comment by nathanwoulfe** [comment]
Thanks @bensheridanreason I'll take a look. 

This is the opposite to what I'd expected - I'd figured it was when sending unsaved content, but sounds like it's an issue in the publish step (I have a feeling it's as simple as events not being fired when the node is published)

I have a couple of other minor fixes pending, so maybe a patch later this week

**Comment by nathanwoulfe** [comment]
@bensheridanreason I think I've tracked this one down, reproducing like this:
- added save hook component to cancel all saves
- verified component code runs when saving a node
- verified component code runs when submitting an unchanged node for publish (runs when workflow completes)
- verified component code runs when submitting a node with pending changes

Issue appears to be in submitting a node with pending changes, where the clientside code submits the node for saving, but the result was ignored, with no notifications shown, then passed on immediately to initiate the workflow. However, when the node progressed to the end of the workflow, the save cancellation should still have happened as the component code would run again, and the node would not be published. 

I've updated the javascript to check the save result before initiating the workflow, and to display the returned notifications. Something seems to be off with the default notification returned for the cancelled save, it's not showing the returned label text, but that looks like an Umbraco rather than Plumber issue.

**Comment by nathanwoulfe** [comment]
[plumber.zip](https://github.com/nathanwoulfe/Plumber-2/files/9137400/plumber.zip)
Attached zip is the latest plumber.js build, please test and let me know if this solves the issue.

**Comment by bensheridanreason** [comment]
Hi @nathanwoulfe 

Tested the js fix and it is stopping the request to publish and showing the correct message. 

That has solved the issue thanks for the quick turn around on this

**Comment by nathanwoulfe** [comment]
Awesome, glad that sorted it. 

You'll be fine to keep using that patched file, the same change will be in the next release.
