### ISSUE TITLE
Request Publish does not save content or warn; request unpublish missing

### ISSUE THREAD

**Issue by Chris-N1** [nathanwoulfe/Plumber-2#19]
Not sure if this is deliberate, but you can now request publish without saving; I think it might be related to permissions, as the request unpublish button also doesn't appear even if the user has the right to unpublish.

This means a user can easily make changes and submit them, but unless they click the "Save" button they'll just be submitting a blank set of changes - there's no warning that they haven't saved their changes so we had users wondering where their changes had disappeared to (Umbraco does warn you if you try to move away from the page, but users assumed that having hit "request publish" the content had also been saved).

Here are the permissions on our "Editors" group - these seem to be correct based on what they were in v7 (now migrated to v8):

![image](https://user-images.githubusercontent.com/46811766/83253079-47d3e900-a1a4-11ea-872d-fd6ec6e7c424.png)

**Comment by nathanwoulfe** [comment]
Hi Chris, definitely not intentional - users should still see the save button where permissions allow (currently not the case on the latest beta), which would alleviate (partially) issues with submitting dirty content, but I'll add a flag to check and auto-save content if it's dirty on submit.

Not related to permissions on your end, but due to me treating an object like a bool and therefore having a null-check always pass. Will fix it up and hopefully call that v1.2.0 and get it shipped...

**Comment by nathanwoulfe** [comment]
Building now - have added auto-saving of dirty content when starting a workflow, plus fixed the missing save button. So can now be saved like normal, or left for workflow to manage internally.

**Comment by Chris-N1** [comment]
Thanks Nathan 👍  - the normal Umbraco Save button was there so users could still save content, but it was a bit easy to forget before submitting!

**Comment by nathanwoulfe** [comment]
Should be all good now in 1.2 - have added dirty-checking when initiating a workflow, which will auto-save if the content has pending changes.
