### ISSUE TITLE
File attachment on workflow initiation

### ISSUE THREAD

**Issue by lordscarlet** [nathanwoulfe/Plumber-2#35]
Our specific requirements specify that an item submitted to be published needs to have an attached file (approval documentation from an external system). I am trying to figure out the best way to do this. Right now I have these options in mind:

1. I am thinking I may be able to do this by subscribing to an event and make it work, but I haven't done that yet with Umbraco. All of the quick documentation I have found is just for doing something in the back end, such as writing to the log. But I am googling to see if I can find a way to initiate an Umbraco dialog between workflow submission and actually putting the request into the database.
2. We could also put a property on every node to attach it, but I think that is less than ideal
3. Some sort of feature request that allows for templating the _Initiate workflow_ screen or to meet this requirement specifically

**Comment by nathanwoulfe** [comment]
It's currently possible to add a template to the initiate workflow comment field - the template is defined in language xml file (so that it's easily localized). Simple formatting only given it's a textarea.

It would be possible to add a feature for attaching documents to a workflow process, it's not on my priority list at the moment though, and would likely not be until after Umbraco 8.7 is released as there are changes in 8.7 which I plan on leveraging, which in turn require updates to Plumber's DB schema and adding supporting-docs to a workflow would also be a DB change, so I'd prefer to do both as part of the same minor version release.

**Comment by lordscarlet** [comment]
Sounds good. I may have to figure out how to hijack things in the meantime.
I appreciate the follow-up, though. Worst case I will just out a property
on my doc types in the short term.

**Comment by nathanwoulfe** [comment]
Hi @lordscarlet just an FYI - v.1.4.0 will include document attachments when initiating a workflow. Will be leveraging the default Umbraco media picker, so user will be able to either select an existing doc or upload their own. The reference to the selected document will be passed through the rest of the workflow stages.

Should be out next week (all going to plan) but beta will be on nuget in a couple of hours from the time of this comment

**Comment by nathanwoulfe** [comment]
Next week became 18 days, but 1.4.0 is out now, including this shiny new feature.
