### ISSUE TITLE
Question: Is there a way to set which groups are admins?

### ISSUE THREAD

**Issue by lordscarlet** [nathanwoulfe/Plumber-2#52]
By default, the administrator group (Umbraco groups, not approval groups) seems to be able to bypass workflow. Is it possible to set other groups to do the same?

**Comment by nathanwoulfe** [comment]
Hi @lordscarlet, works like this - Umbraco admin group is given access to the Workflow section when Plumber is installed, because that makes sense and follows Umbraco's pattern where admins see everything. Plumber treats any user with access to the Workflow section as a admin, in the context of workflow actions, allowing them to bypass/cancel/action workflows not directly assigned to them.

So, what you could do would be create an Umbraco group 'Workflow admins' or similar, with access only to the Workflow section, then add users to that group. Should get the result you need.
