### ISSUE TITLE
Approver message no longer visible after approval

### ISSUE THREAD

**Issue by Chris-N1** [nathanwoulfe/Plumber-2#55]
**Describe the bug**
Approval message no longer appears after workflow approval

**To Reproduce**
As a user without workflow permissions, submit a publish request - see that the publish request is submitted
Log off.
Log on as a user with permission to approve the change
When you approve it now takes you straight to the "Submit" page without changing the

**Expected behavior**
In 1.3.8, the "Approve" page would remain visible and the approver's message could be seen against it - this is the expected behaviour.

**Screenshots**
Before approval:
![image](https://user-images.githubusercontent.com/46811766/98371452-1b19dc80-2034-11eb-9058-9a80dbe38c35.png)

Straight after approval:
![image](https://user-images.githubusercontent.com/46811766/98371634-66cc8600-2034-11eb-97d0-8c7d72ad045c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10/macOS
 - Browser Chrome/Safari/Edge/Firefox

**Plumber version**
1.4.2+ (may be earlier - we upgraded from 1.3.8 to 1.4.2).

**Additional context**
We are using Umbraco 8.6.4 if that makes a difference - I have tested this on a fresh install with this version where Plumber is the only plugin installed.

**Comment by nathanwoulfe** [comment]
Hi @Chris-N1 this is working correctly - when a task is approved, and that approval completes the workflow, the app routes back to the submit view. If the approval results in a new approval task (ie it wasn't the final step in the workflow), the app stays on the same view, allowing the user to action the new task if they have permission to do so.

In previous versions there were issues with SignalR disconnecting so the app state wasn't updated correctly, this was fixed in 1.4.0 (or 1.4.1, can't remember which).
