### ISSUE TITLE
Extending the plugin's functionality

### ISSUE THREAD

**Issue by piotrkrajewskicn** [nathanwoulfe/Plumber-2#62]
Hi!

Not sure if it's the right place to write my question but got no other option, I suppose ;)

My client has come up with some specific requirements when it comes to an approval flow. To simplify, let's imagine this kind of a scenario: a user wants to approve a content but to do it, they need to select an additional checkbox saying something like "I accept conditions [...]". Basicaly we'd need some kind of **a form with a custom logic and validation** before we allow the user to click "Accept" or/and "Reject" button. 
Of course I can imagine it's not something you'd want to implement in your plugin, but is there any way to extend it so we could write our custom code doing something similar to what I described above? Maybe some kind of an on click action for the buttons which we could subscribe to and display a modal and then trigger the button action?

Thanks for help in advance!

**Comment by nathanwoulfe** [comment]
@piotrkrajewskicn that's an interesting one - you're correct in that it would be something I'd add to the core package. I could add events that you could hook into to then show the modal, but I don't know how I'd handle the action your user takes in the modal (ie accepting/rejecting the conditions) because my event wouldn't be aware of any subscribers, and if it was, it wouldn't know how the subscriber was implement, so wouldn't know what action to take.

Unless you're planning on persisting the accept/reject in your modal, I'm not sure it really adds anything - you'd have no record of a user accepting the conditions other than the workflow being processed.

And having written that, I might have an alternative idea - it's possible to use templates in the comment text when submitting a workflow, but only on the initial submission (not on approval steps). If that's enough, you could write your text into a comment template, which would be submitted as part of the workflow. If it needs to be every step, I could make the template configurable (displayed either on initial submission or every step).

**Comment by piotrkrajewskicn** [comment]
Thanks for the answer! I think your first sugestion would work best, I'd imagine that I could subscribe to an event which would provice me with callbacks like in a standard js promise, so I could do something like:

```
onApproving((actionName, resolve, reject) => {
  if (actionName === 'accept') {
    //displaying a custom modal (where I could also do my own calls to save additional data) and then either resolving (approving the accept) or rejecting (not allowing to perform approve action)
  }
})
```

It seems like that approach could be quite flexile and not too hard to implement, what do you think?
