### ISSUE TITLE
After creating/deleting approval group list does not automatically update

### ISSUE THREAD

**Issue by jenluong-deepend** [nathanwoulfe/Plumber-2#7]
Versions
Fresh install of Umbraco: 8.3.0 & Plumber: 1.0.4

Issue
When adding/deleting an approval group, list doesn't automatically update until you do a page refresh. 

![image](https://user-images.githubusercontent.com/40009643/68913334-03a46c80-07af-11ea-9dec-40280cb6fa0c.png)

If you also switch to a content node right after (without refreshing) and try to configure the Content approval flow, the approval group list isn't updated with the added/deleted group. Group appears/disappears after the page refresh is done.

![image](https://user-images.githubusercontent.com/40009643/68913602-ed4ae080-07af-11ea-901b-b9b16ed2a4ea.png)

**Comment by nathanwoulfe** [comment]
That's a bit annoying isn't it... I've changed the group creation flow, so where it previously caused a reload due to using an old dialog, that not longer happens. Will need to plug in some event management stuff to refresh the data table. 

From memory, the group info on the content node is cached on the client. Need to invalidate that when a group is added or removed, and push new data into the content app. 

Weekend jobs.

**Comment by nathanwoulfe** [comment]
@jenluong-deepend also fixed in 1.0.5 - please confirm. 😃
