### ISSUE TITLE
Provide better context when reviewing requests

### ISSUE THREAD

**Issue by lordscarlet** [nathanwoulfe/Plumber-2#81]
**Describe the solution you'd like**
We have over 25,000 published nodes on our single Umbraco site. This means that knowing the context of a node is very difficult when the only thing you have is a page name. Things like "2020" or "Contact Us" are repeated many times throughout the site. It also means that the person performing the approval is not necessarily widely versed in all of the content.

When reviewing items submitted for approval, the only context provided is the page name, change description, and workflow activity.
![image](https://user-images.githubusercontent.com/17951/112679927-20d95880-8e43-11eb-8a7c-7fe22b7d8123.png)

I would like to see at least 1 of 2 things:

1. Some sort of hint as to where in the site it is coming from. A miniature tree, bread crumbs, a URL path, something
2. The ability to navigate to the node within the tree (in other words, navigate to `/umbraco/#/content/content/edit/22540`)

**Describe alternatives you've considered**
On the workflow dashboard, the dialog provided by the Detail button gives you access to a Preview button. This is helpful, however, preview does not give the published URL, which is sometimes needed to provide context. In addition, as per #80 , this functionality is not always available when viewing workflow information outside of the Cotnent tree.

**Licensed version?**
Yes

**Comment by nathanwoulfe** [comment]
@lordscarlet I've updated the dialog to include the url as the header description (in place of 'Action: Publish'), and shifted the action into the dialog title. Also added a go to node button next to preview, which is displayed only when the dialog is opened from a dashboard (as there's no value in showing it in the content app since we're already on the node)

Will be in tonight's nightly, then released in 1.5.3/1.6.

**Comment by nathanwoulfe** [comment]
Fixed in 1.5.3
