### ISSUE TITLE
No validation for length of description

### ISSUE THREAD

**Issue by lordscarlet** [nathanwoulfe/Plumber-2#82]
**Describe the bug**
When initiating a workflow, there is no validation for the length of the description field.

**To Reproduce**
1. Request publish on a node
2. Enter a lot of text into "Describe the changes"
3. Click "Request publish"
4. Receive an error and lose any content entered `Could not initiate workflow: string or binary data would be truncated`

**Expected behavior**
A validation message that indicates the text is too long, and an indication as to the max length of the content.

Additionally, if not taken care of here, I am going to request a lot more characters in that field. :) 

**Screenshots**
![image](https://user-images.githubusercontent.com/17951/112680798-313e0300-8e44-11eb-8f2c-07360d93d41e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome [e.g. chrome, safari]
 - Version 89

**Plumber version**
v1.5.1.509

**Licensed version?**
Yes

**Comment by nathanwoulfe** [comment]
@lordscarlet this one is confusing - the column is varchar(max) so should have no issues with storing long data. Strangely though if I try to insert a long string into that column via Linqpad/SSMS I get the same error so I'm thinking it's less likely a code issue as it is a schema problem. Don't really want to switch to ntext given it's deprecated, but if that fixes the issue, I guess that's an easy win

**Comment by nathanwoulfe** [comment]
Annnd it's probably due to Umbraco having to support SQLCE, which doesn't support nvarchar(max). 

ntext it will have to be - I'll do this in the 1.6 minor, as there is already a migration task for that release. Changing the column type will remove the need for a character count, as the field will store way more than any editor is going to type.

**Comment by lordscarlet** [comment]
That seems like a good compromise. Not being able to use varchar(max) is unfortunate, but you're right, an editor shouldn't run out of characters.

**Comment by NikRimington** [comment]
I've started seeing this error as well:

String or binary data would be truncated in table 'dbo.WorkflowInstance', column 'AuthorComment'. 

An option to help would be to actually put a limit on the length of the comment and give feedback to the editor rather than a complete failure? That error message isn't that helpful especially as there is no feedback to indicate what length would be acceptable.

**Comment by nathanwoulfe** [comment]
Hey @NikRimington the fix for this is on the way in 1.6, needs a column migration to change the type. I think the latest nightly includes the change, but might still have some other issues so wouldn't be prod-ready yet. 

If it's urgent, you should be able to change the column type yourself, with no side affects.

**Comment by nathanwoulfe** [comment]
Fixed in v1.6.0
