### ISSUE TITLE
Error when running test license on non-localhost domain

### ISSUE THREAD

**Issue by WayneKruger** [nathanwoulfe/Plumber-2#86]
**Describe the bug**
When the test license is present and you try to access the Umbraco CMS on a non-localhost domain, you are presented with a blank screen (just the Umbraco CMS header is visible.

**To Reproduce**
1. Make sure the test license is present
2. Access the CMS via a non-localhost domain (e.g site.localtest.me)

**Expected behavior**
Should the CMS not still be functional but with a trial license?

**Screenshots**
![image](https://user-images.githubusercontent.com/4264302/119959268-228ade00-bfa4-11eb-9ca8-56507b2a1f76.png)
![image](https://user-images.githubusercontent.com/4264302/119959376-3df5e900-bfa4-11eb-9412-4e4758207425.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge
 - Version 90.0.818.66

**Plumber version**
1.6.1 and 1.6.2

**Licensed version?**
No

**Additional context**
When looking at the network tab on the browser, I see there is a error 500 to ~/umbraco/ServerVariables, when accessing that I get an error message:

`[UriFormatException: Invalid URI: The hostname could not be parsed.]    System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind) +261    Plumber.Core.Models.Licensing.PlumberLicense.IsLicensedDomain() in D:\a\1\s\Plumber.Core\Models\Licensing\LicenseModels.cs:97    GetIsLicensed(Object ) +76    Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object target) in /_/Src/Newtonsoft.Json/Serialization/DynamicValueProvider.cs:110  [JsonSerializationException: Error getting value from 'IsLicensed' on 'Plumber.Core.Models.Licensing.PlumberLicense'.]`

**Comment by nathanwoulfe** [comment]
Hi @WayneKruger, this is due to the subdomain - the test license will be ok on any domain ending `.test` or `.local`, or `localhost` or `localtest`, with no subdomain. 

Admittedly it's a bit flakey, and will have some changes as part of the V9 version which will be backported to V8. Really should be doing some pattern matching on combinations of localhost/localtest, and .test, .local, .me, or something to that affect. Easiest solution for you for now though would be to serve from localtest.test or localtest.local

**Comment by nathanwoulfe** [comment]
Will have a fresh nightly up soon with improved domain handling

**Comment by WayneKruger** [comment]
Great thanks. 

So for running the trial version on a non local domain, do I then just remove the license file? I am trying to determine whether my client will need to purchase a license or if the standard one will do but I am unable to figure out how to set up a 2 step approval flow with the unlicensed version. I was able to do it easily with the test license.

Sorry this is perhaps not the right forum for it. Was more trying to determine if the trial functionality is still there when the license file is removed or does it need a trial license file.

**Comment by nathanwoulfe** [comment]
Hi @WayneKruger, that's correct - the test license is only used to unlock the paid features for evaluation on local sites. Removing it will revert to the default features (will need to restart the site since the license is checked on boot). 

Re the 2-step approval, what issues were you having? Flows on content types require a license, node-level flows are always available.

**Comment by WayneKruger** [comment]
I'm trying to figure out how to enable a node level workflow . I have the 2 approval groups set up but where do I enable the workflow for a specific node?

**Comment by nathanwoulfe** [comment]
You'll do that on the node itself, on the workflow content app (there will be a config tab with options for setting the workflow, plus showing any inherited or content-type flows applied to the current node)

**Comment by WayneKruger** [comment]
Silly me. I didn't have any properties defined on the content type yet so the Workflow tab was not visible. Thank you so much for your help!

**Comment by nathanwoulfe** [comment]
Ah yeah, that'll do it! 😄
